name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker compose -f ./ci/docker-compose.yaml up -d
      
      - name: check docker compose status
        run: docker compose -f ./ci/docker-compose.yaml ps

      - name: Test the build
        run: healthcheck.sh ci-kpivisualization-frontend-1 120
        #docker run --network container:ci-kpivisualization-frontend-1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/
